In [6]:
import numpy as np

try:
    # Array 'a' has shape (3,) - a 1D array
    a = np.array([1, 2, 3])
    
    # Array 'b' has shape (3, 1) - a 2D column vector
    b = np.array([[1], [2], [3]])
    
    # Attempting addition
    result = a + b
    
    print("Result of addition:")
    print(result)

except ValueError as e:
    print(f"Broadcasting error: {e}")

Result of addition:
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [7]:
import numpy as np

# Generates a 3x3 identity matrix (1s on the diagonal, 0s elsewhere)
identity = np.eye(3)

# A standard 3x3 matrix
matrix = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])

# Matrix addition
result = matrix + identity

print("Matrix + Identity:\n", result)

Matrix + Identity:
 [[ 3.  3.  4.]
 [ 1.  1.  6.]
 [ 7.  8. 10.]]


In [8]:
import numpy as np

# An array containing a Not-a-Number (NaN) and an Infinity (inf)
data = np.array([1, 2, np.nan, 4, np.inf])

# np.isfinite returns False for NaN and Inf; True for normal numbers
cleaned = data[np.isfinite(data)]

print("Cleaned Data:", cleaned)

Cleaned Data: [1. 2. 4.]


In [9]:
import pandas as pd

# Creating a DataFrame with missing values (None)
df = pd.DataFrame({
    "Name": ["Kurt", "Marck", "Daddy Bao", "Joecel"],
    "Score": [85, None, 92, 88]
})

# Removing any row that contains at least one missing value
df_cleaned = df.dropna()

print("Cleaned DataFrame:\n", df_cleaned)

Cleaned DataFrame:
         Name  Score
0       Kurt   85.0
2  Daddy Bao   92.0
3     Joecel   88.0


In [10]:
import pandas as pd
import numpy as np

# Creating a simple numeric DataFrame
df = pd.DataFrame({
    "X": [1, 2, 3],
    "Y": [4, 5, 6]
})

# Applying NumPy's log and square root functions directly to columns
df["Log_X"] = np.log(df["X"])
df["Sqrt_Y"] = np.sqrt(df["Y"])

print("Transformed DataFrame:\n", df)

Transformed DataFrame:
    X  Y     Log_X    Sqrt_Y
0  1  4  0.000000  2.000000
1  2  5  0.693147  2.236068
2  3  6  1.098612  2.449490
