In [2]:
import numpy as np

# Personal Information
STUDENT_NAME = "Aisy Cordero"
# Extracting the numerical part of the ID for the seed
STUDENT_ID = 250354

# Setting the seed for reproducibility
np.random.seed(STUDENT_ID)

# Generating the 1D array
# The upper bound is (250354 % 100) + 50 = 54 + 50 = 104
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

# Computing statistics
mean_val = np.mean(data)
std_val = np.std(data)

print("Mean:", mean_val)
print("Std Dev:", std_val)


Aisy Cordero's Array: [  3  26  41  75  21 103  49  43  84  58]
Mean: 50.3
Std Dev: 29.00017241328058


In [3]:
import numpy as np
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)
# Upper bound: (250354 % 50) + 20 = 4 + 20 = 24
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Aisy Cordero's Matrix:
 [[ 3  9 11 21]
 [ 7 17 11 20]
 [17  5 18 19]]
Row sums: [44 55 59]
Column sums: [27 31 40 60]


In [4]:
import numpy as np
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)
# Upper bound: (250354 % 20) + 10 = 4 + 10 = 14
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:, 1, :]
print("Slice[:, 1, :]:\n", slice_mid)

Aisy Cordero's 3D Array:
 [[[ 2  8 10]
  [20  6 16]
  [10 19 16]]

 [[ 4 17 18]
  [ 0  0 18]
  [ 8 19  7]]

 [[ 5  4  7]
  [22  7 12]
  [20  2 15]]]
Slice[:, 1, :]:
 [[20  6 16]
 [ 0  0 18]
 [22  7 12]]


In [5]:
import numpy as np
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)
# Upper bound: (250354 % 100) + 50 = 4 + 50 = 54
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)

# Filter: (Value > 250354 % 50 [which is 4]) AND (Value < 250354 % 100 [which is 54])
filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]

print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Aisy Cordero's Original: [  3  26  41  75  21 103  49  43  84  58]
Filtered subset: [26 41 21 49 43]


In [6]:
import numpy as np
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)
# Upper bound: (250354 % 50) + 20 = 4 + 20 = 24
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)

print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[ 3  9]
 [11 21]]
Matrix B:
 [[ 7 17]
 [11 20]]
A @ B:
 [[120 231]
 [308 607]]
Determinant of A: -36.000000000000014


In [7]:
import numpy as np
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

# Generate 8 evenly spaced angles from 0 to 2*pi
angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)

print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Aisy Cordero's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [8]:
import numpy as np
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)
# Upper bound: 24
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))

# Modify: Every 2nd row and every 2nd column set to 0
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Aisy Cordero's Modified 4x4 Array:
 [[ 0  9  0 21]
 [ 7 17 11 20]
 [ 0  5  0 19]
 [ 1  1 19  9]]


In [6]:
import numpy as np
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)



Aisy Cordero's Scores: [  2  25  40  74  20 102  48  42  83  57]
Grades: ['Fail' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [9]:
import numpy as np
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened array:\n", flat_arr)
print("Transposed array:\n", transposed_arr)



Original array:
 [[ 3  9 11 21]
 [ 7 17 11 20]
 [17  5 18 19]]
Flattened array:
 [ 3  9 11 21  7 17 11 20 17  5 18 19]
Transposed array:
 [[ 3  7 17]
 [ 9 17  5]
 [11 11 18]
 [21 20 19]]


In [10]:
import numpy as np
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[ 3  9 11]
 [21  7 17]
 [11 -1 17]]


In [11]:
import numpy as np 
import pandas as pd
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME]*5,
    'Score': np.random.randint(STUDENT_ID%50, STUDENT_ID%100+50,5)
})
print(df)

           Name  Score
0  Aisy Cordero      6
1  Aisy Cordero     29
2  Aisy Cordero     44
3  Aisy Cordero     78
4  Aisy Cordero     24


In [12]:
import numpy as np
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor    98609.5
Master      81815.5
PhD         83944.0
Name: ConvertedComp, dtype: float64


In [14]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)

# Creating a DataFrame with random compensation data
df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Sorting by compensation in descending order to find top earners
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(f"{STUDENT_NAME}'s Top 5 Compensation:\n", top5)

Aisy Cordero's Top 5 Compensation:
        Country  ConvertedComp
0  Philippines         106969
3       Canada          90250
4      Germany          87664
2           UK          83944
1          USA          75967


In [15]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)

# Creating data for 5 employees
df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    # Random years of experience: (0 to (250354 % 20 + 10)) = 0 to 24
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})

# Threshold check: ID % 10 = 7
# We only want developers with more than 7 years of experience
high_exp = df[df['YearsCodePro'] > STUDENT_ID % 10]
print(f"{STUDENT_NAME}'s High Experience Employees:\n", high_exp)

Aisy Cordero's High Experience Employees:
            Name  YearsCodePro
1  Aisy Cordero             8
2  Aisy Cordero            10
3  Aisy Cordero            20
4  Aisy Cordero             6


In [1]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)

# Random compensation values
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50k-100k', '100k-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)


   ConvertedComp    Bracket
0         106969  100k-150k
1          75967   50k-100k
2          83944   50k-100k
3          90250   50k-100k
4          87664   50k-100k


In [17]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)

# Using a functional salary range as corrected in the manual
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

# Applying log transformation
df['LogComp'] = np.log(df['ConvertedComp'])

print(f"{STUDENT_NAME}'s Log Transformation:\n", df)

Aisy Cordero's Log Transformation:
    ConvertedComp    LogComp
0         106969  11.580294
1          75967  11.238054
2          83944  11.337905
3          90250  11.410339
4          87664  11.381267


In [14]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5), # 0 to 27
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate the correlation between the two variables
corr_matrix = df.corr()

print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.645812
ConvertedComp      0.645812       1.000000


In [19]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)

# Creating a DataFrame with Education Levels and random Salaries
df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()

print(f"{STUDENT_NAME}'s Grouped Summary Statistics:\n", summary)

Aisy Cordero's Grouped Summary Statistics:
     EdLevel     mean   median           std
0  Bachelor  98609.5  98609.5  11822.118275
1    Master  81815.5  81815.5   8271.028020
2       PhD  83944.0  83944.0           NaN


In [20]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)

# Generate salaries based on your student ID seed
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

threshold = 110000

# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(f"{STUDENT_NAME}'s Salary Classification:\n", df)

Aisy Cordero's Salary Classification:
    ConvertedComp HighPay
0         106969      No
1          75967      No
2          83944      No
3          90250      No
4          87664      No


In [21]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Aisy Cordero"
STUDENT_ID = 250354

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean', 'max'])

print(f"{STUDENT_NAME}'s Country Statistics:\n", top_countries)

Aisy Cordero's Country Statistics:
                  mean     max
Country                      
Canada        90250.0   90250
Germany       87664.0   87664
Philippines  106969.0  106969
UK            83944.0   83944
USA           75967.0   75967
